.pylintrc
plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/integration.sh
test/integration/test_koji.py

Move to a python based integration test suite, which is more flexible and extensible than running tests directly from `integration.sh`. Also fix various style issues and add documentation.

Use python based integration test and various cleanup and fixes

---

test/unit/plugintest.py
test/unit/test_builder.py
test/unit/test_cli.py
test/unit/test_hub.py

Add the skeleton to run the cli plugin unit tests. As first check ensure that exceptions are thrown for the build target checks.

Unit test skeleton for the command line interface plugin

---

container/builder/Dockerfile
koji-osbuild.spec.in
plugins/builder/osbuild.py
run-tests.sh
test/Dockerfile
test/unit/test_builder.py

Use the more convenient `requests` package and add more builder unit tests, e.g. test a successful compose.

Use requests python package and add more builder unit tests

---

.github/codecov.yml
plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/unit/test_builder.py
test/unit/test_hub.py

Currently we were passing the repo information as a comma separated string, which is fragile, since urls can contain commas. Just transfer them as arrays of strings.

Transmit user specified repos as array of strings

---

plugins/builder/osbuild.py
test/unit/test_builder.py

When returning the result from the task handler function, return a more complete and structured object in all cases. Instead of a normal task return with a result dictionary, raise an exception when the compose failed.
Closes #15

Better task return value, throw exceptions on build failures

---

plugins/builder/osbuild.py
test/unit/test_builder.py

After creating the compose request object, save it as meta-data of the task. This should come in especially handy when a compose gets rejected by osbuild-composer.

Save the compose request json

---

HACKING.md
container/builder/osbuild-koji.conf
container/hub/hub.conf
make-tags.sh
plugins/builder/osbuild.py
run-koji-container.sh
schutzbot/repos/fedora/32/osbuild-composer.repo
schutzbot/repos/rhel/8.2/osbuild-composer.repo
test/build-container.sh
test/data/osbuild-composer.toml
test/integration.sh
test/integration/test_koji.py
test/unit/test_builder.py

Upstream composer has introduce a few changes that we need to adapt for:
- the koji composer API is now exposed on the standard https port (443). Thus koji hub and web need to move to a different pair: 8080 (http) and 4343 (https). Change the scripts and tests for that
- the koji API gained a prefix 'api/composer-koji/v1/'. Change client and unit tests to use that prefix. Use urljoin to create new APIs
- composer configuration format (osbuild-composer.toml) has changed and now also includes configuration for the CA and allowed domains
- update the composer RPM repositories to the commit for the 21 upstream release.

Sync with composer 21 changes

---

HACKING.md
README.md
container/builder/osbuild-koji.conf
plugins/builder/osbuild.py
test/unit/test_builder.py

Mostly to be more in line with how things are called in all other koji configuration files. Updates to the docs.

Use server instead of url for builder configuration

---

test/unit/test_builder.py

Although in that specific use case it was fine, since the list was copied before usage, pylint in newer versions was unhappy.

test/builder: avoid using list in keyword argument

---

koji-osbuild.spec.in

The hub plugin uses jsonschema, so it must explicitly depend on it.

spec: require python3-jsonschema (hub plugin)

---

plugins/builder/osbuild.py
test/unit/test_builder.py

This is based on PR #30. The actual fix, done by @tkopecek is exactly the same, only the commit message was modified and a test added that would have caught the bug (and should help prevent regressions).
See the commit message for details. Many thanks @tkopecek

Fix support architecture check in builder plugin

---

.github/workflows/ci.yml
README.md
test/container/hub/kojiweb.conf

Integrate the codespell github action to spell check the source code in CI. Fix uncovered mistakes and also some links in `README.md`.

Integrate spell checking via codespell and fix uncovered mistakes

---

HACKING.md

Make the destination of the link be an absolute path, but more importantly fix the actual path the plugin gets installed in.

HACKING.md: fix client plugin install instructions

---

test/run-koji-container.sh

The official postgres container image is fetched from docker.io, which recently introduced rate limiting, which makes introduces possible CI error if we run into this limit. Instead use a custom mirror[1] of the official image, hosted on quay.io[2]. As a side effect this updates the posgres version from 12 to 13.
[1] osbuild/containers@7db3c68
[2] quay.io/osbuild/postgres:v1

test: use quay mirror for the postgres container

---

plugins/builder/osbuild.py
test/unit/test_builder.py

Use the new composer API to fetch and upload logs. Additionally also upload the compose status and update it throughout the build.

Upload logs and the compose status

---

plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/unit/test_builder.py
test/unit/test_cli.py
test/unit/test_hub.py

Add a new command line option `--skip-tag` that will skip tagging after a successful build. The help text is copied from the same option of other sub-commands in the koji client. The hub plugin's jsonschema was updated accordingly, and the builder plugin will skip the tag if the option was requested.
Tests were added or augmented for all three plugins to test the new option.

plugins: ability to skip the tagging

---

.github/workflows/ci.yml
plugins/builder/osbuild.py
test/unit/test_builder.py

Instead of getting the `koji_build_id` from the direct reply of the compose request call, use the one returned in the compose status.
The reason behind this is that composer was changed so that the `CGInitBuild` call to koji is now being done by a worker and not composer itself. This means that once the compose request call returns, the build id is not yet known. In composer release 24, the compose request call internally waits for the worker that does the `CGInitBuild` API call, but that will be changed, and the `koji_build_id` will then not be returned from the compose request API call anymore. This prepares for that. The tests are also adapted to simulate the new behavior.
NB: this makes composer 24 a dependency, since the build id is taken from the `ComposeStatus`, which was only …

Use dynamic build id

---

plugins/builder/osbuild.py
test/unit/test_builder.py

De-serialize the koji init and import logs, required fields in the `ComposeLogs`, and if non-empty, attach them to the task. Update the tests to check for the presence of these logs.

builder: attach koji init/import logs

---

test/build-container.sh
test/container/builder/Dockerfile.fedora
test/container/builder/Dockerfile.rhel
test/container/builder/run-kojid.sh
test/container/hub/Dockerfile.fedora
test/container/hub/Dockerfile.rhel
test/container/hub/run-hub.sh
test/make-tags.sh
test/run-builder.sh
test/run-koji-container.sh

The main reason behind this is that currently we were using `latest`, which is a moving target. Now, the containers are matched to the host. This should also allow us to use the testing infra in gating tests, assuming that the gating machines run the target operating system version. See individual commits for more details.
Additionally make a few minor changes to re-enable local development.

Match container versions to the host

---

koji-osbuild.spec
meson.build
schutzbot/Jenkinsfile
schutzbot/deploy.sh
schutzbot/mockbuild.sh

Most of these commits come from similar ones on osbuild-composer, only amended for the use of `meson` here. Please see individual commits.

mockbuild: make more consistent with other osbuild projects

---

test/Dockerfile
test/container/builder/Dockerfile.fedora
test/container/hub/Dockerfile.fedora

In order to avoid running into docker.io's new download limit, use the container directly from registry.fedoraproject.org.

test: replace docker.io with fedora's registry

---

test/integration.sh

The current one is not available anymore. We cannot use rpmrepo for this
yet, because the podman-plugins package is too new.

test/integration.sh: bump nightly

---

schutzbot/deploy.sh
test/integration.sh
test/run-koji-container.sh

The nightly disappeared again. We now have an 8.4.0 snapshot that contains the package. Let's use it.

assorted CI fixes/improvements

---

.gitignore
plugins/builder/osbuild.py
test/unit/test_builder.py

Add support for fetching manifests via the compose/<id>/manifests API endpoint. A failure to fetch them is not critical, since it is possible the manifests don't exist, e.g. when depsolving fails. The manifest is attached per image request.

Fetch and attach the manifests

---

plugins/cli/osbuild.py

Remove the single string type annotation; it does not gain us much and seems to be the only thing missing for python 2.7 (RHEL 7) support.

plugin/cli: remove type annotation

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/trigger-gitlab.yml

There isn't a requirements.txt file for the Python dependencies so only GitHub Actions will be monitored and updated.

Enable Dependabot

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
run-tests.sh

Add support for coding in VS Code via a Dev Container. Allow `run-test.sh` to run from within the container.

devcontainer: add initial support

---

.devcontainer/Dockerfile
.pylintrc
plugins/builder/osbuild.py
setup.cfg

Also include `openssl` in the dev container and move the pylint configuration to `setup.cfg`.

Fix command line argument names

---

plugins/cli/osbuild.py

This got deprected upstream[1] and now spits out a warning.
[1] https://pagure.io/koji/c/32b5377392ade0f1d1e159288b000383e5c3a39b

cli: do not use translation helper

---

schutzbot/deploy.sh

osbuild 30 is quite old, use a new one.

schutzbot: update osbuild to 46

---

.gitlab-ci.yml
test/integration/test_koji.py
test/make-tags.sh

Change the integration test so that it adapts to the host, i.e. it will take the name, version and architecture for the tags and urls for the repos from the host it is running on. This should make it more future proof since we now have a central place where this is configured: the ci configuration, i.e. `.gitlab-ci.yml`.

ci: integration tests now adapt to the host

---

koji-osbuild.spec
plugins/builder/osbuild.py
schutzbot/deploy.sh
test/container/builder/osbuild-koji.conf
test/data/osbuild-composer.toml
test/integration.sh
test/run-openid.sh
test/unit/test_builder.py

Implement support for authentication via OAuth2 using the client credentials "Client Credentials Grant" flow (4.4 of RFC [6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4)). For this a new configuration section is added to the config file, where the client_id, client_secret and token_url have to be specified.
The implementation does currently not support "refresh tokens", but does support refreshing the token if an `expires_in` is present in the token itself.
Corresponding unit tests have been added.

Support for oauth2 authentication

---

HACKING.md
plugins/builder/osbuild.py
plugins/cli/osbuild.py
schutzbot/deploy.sh
test/unit/test_builder.py
test/unit/test_cli.py

Port the plugin to use the Composer's cloud API.
Needs osbuild/osbuild-composer#2214

builder: use cloud api

---

plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/unit/test_builder.py
test/unit/test_cli.py

OStree compose requests need special options, like the `ref` the
`parent` and the `url`. Add support for those options to all three
plugins:
- The command line plugin now takes `--ostree-{parent,ref,url}` and passes it to koji via the existing options dictionary.
- The JSON schemata in the hub plugin was adjusted to allow these new options.
- Finally the builder plugin will look for the new `ostree` dict inside the options, create an `OSTreeOptions` object from it, and attach it to each image request.
NB: since the ostree options are per image request and are thus architecture dependent we support a "$arch" substition in the `parent` and `ref` options that will be resolved by the plugin; this allows to builds arch specific commits for with a single compose request.
Add the respective unit …

plugins: support for ostree specific options

---

.github/workflows/release.yml
.packit.yaml

I have already enabled packit-as-a-service in the osbuild organisation settings.
This is currently blocked by: https://github.com/osbuild/release-action/pull/4

Add upstream release bot and enable packit

---

plugins/builder/osbuild.py

It similar to BuildTask - so it doesn't do much on the builder and
doesn't use a lot of resources. It makes sense to have much lower weight
for this type of task.

Lower task weight

---

koji-osbuild.spec

This is necessary once so we can enable the upstream release bot workflow,
which consists of just pushing a tag and bumping the version number
directly after the release is done.

Pre-release version bump

---

plugins/builder/osbuild.py
test/unit/test_builder.py

Use the `self.secret` and not `self.id` for the secret. Doh. Mea culpa. Fix the corresponding test as well, which also checked for the wrong thing.

builder: use correct secret when fetching token

---

test/container/builder/osbuild-koji.conf

configparser treats quotes literally:
client_id = "koji"
translates to the following python string:
'"koji"'
This doesn't matter in the test because the oauth mock from osbuild-composer
actually ignores the credentials and return the token in every case.
But if you want to take this config as an example, you will probably put the
credentials automatically inside the quotes which will not work because a real
oauth server will refuse the client ID surrounded by quotes.
Note that .conf works different than .toml:
TOML requires to have strings in quotes. Yeah, consistency. 🤷

test/builder: drop misleading quotes from config

---

koji-osbuild.spec
schutzbot/mockbuild.sh

koji-osbuild-tests is dependent on osbuild-composer-tests but this package
is not shipped into Fedora because it provides zero value to users.
Let's do the same for koji-osbuild. koji-osbuild-tests will be built only
in our upstream CI but not built in the official Koji.

spec: don't push tests into Fedora

---

plugins/builder/osbuild.py

We decided to do this late change to Cloud API in order to keep the field name
same for all the APIs:
https://github.com/osbuild/osbuild-composer/pull/2479
I strongly believe that gpgkeys are not used in any of the current koji-osbuild
deployments yet so this change should be safe.

builder: rename gpg_key field to gpgkey for repos

---

README.md
plugins/builder/osbuild.py
test/unit/test_builder.py

We need koji-osbuild-builder to be able to connect to composer via a proxy
because koji builders in our internal deployment cannot reach
api.openshift.com directly. This commit adds a new option `proxy` to the
builder plugin config that controls whether a proxy is used to route all
requests to composer.
~I'm not sure if the integration test that I designed will work, will see. :shrug: I'm open to suggestions.~

builder: add support for proxying requests to composer 

---

plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/unit/test_builder.py
test/unit/test_cli.py

The Cloud API supports passing in a variety of image customizations, like e.g. extra packages or pre-defining users.
Add a new command line option to the client `--customizations` which takes a path to a JSON file which contains the customziations; they will be passed via the existing `opts` argument to the hub.
Add support for `customizations` to the `opts`/`options` arguments to the hub plugin. No validation to the object is done. Instead we rely in Composer for the validation of the content.
Add support for `customizations` the image `ComposeRequest` in the builder plugin. All specified values are just passed through to composer as-is.
Add tests for the respective plugins.

plugins: add support for customizations

---

plugins/builder/osbuild.py
test/unit/test_builder.py

The status calls are sometimes failing on:
upstream connect error or disconnect/reset before headers. reset reason:
connection termination
Since all requests are going through the company proxy, I think that the
networking isn't working 100% reliably. This commit adds a retry mechanism
provided by the urllib3 library. It will retry on all networking issues and
also on some 5xx errors that makes sense to retry (like gateway failures).
A test is added that runs the compose waiting code against a mock server
that fails every second request. This is imho sufficient to mimick a flaky
networking.

builder: add retries to composer API calls

---

.github/workflows/ci.yml
koji-osbuild.spec
plugins/builder/osbuild.py
plugins/cli/osbuild.py
plugins/hub/osbuild.py
test/copy-creds.sh
test/integration.sh
test/integration/test_koji.py
test/make-tags.sh
test/unit/test_builder.py

- Add support for specifying upload options on Koji CLI and thus upload the built image directly to the cloud as part of the build task. One can currently specify only one upload options, which will be used to upload all resulting images (image types x architectures matrix) to the cloud.
- Extend the integration test to test cloud upload with AWS image. The test case fetches relevant information from Koji to identify the image and then checks that it exists in AWS. The image is then deleted.
- Extend unit tests to cover the newly added functionality.

Support specifying upload options for image builds

---

.packit.yaml
test/container/builder/run-kojid.sh
test/container/hub/run-hub.sh

This enables Bodhi updates created by packit (see https://packit.dev/docs/configuration/#bodhi_update).
It is preferable at this time to switch to packit because fedora-bot got blocked by authentication changes to Bodhi, so we need to manually publish all updates (until the auth method in Bodhi is fixed). See https://github.com/osbuild/fedora-bot/issues/41
We've been trialing this packit workflow in osbuild-composer for a while already successfully (https://github.com/osbuild/osbuild-composer/blob/main/.packit.yaml#L22).

packit: Enable Bodhi updates workflow

---

plugins/hub/osbuild.py
test/unit/test_hub.py

The support for specifying multiple `image_types` for a single compose
has been removed by [1]. This turned out to be problematic, because e.g.
Pungi uses the array type when triggering image builds via osbuild.
Bring back the support for specifying the `image_type` as an array, but
restrict it to a single item. This will cover the Pungi use-case, since
it is always passing a single `image_type` in the array. The array is
then converted to a string in the Hub plugin and passed as such to the
Builder plugin.
Extend unit tests covering the introduced compatibility layer.
[1] https://github.com/osbuild/koji-osbuild/commit/c7252650814f82281ee57b598cb2ad970b580451

Hub: support `image_type` being an array for backwards compatibility

---

.github/workflows/ci.yml
plugins/builder/osbuild.py
plugins/hub/osbuild.py

In order to track service level indicators, we need to print more logs.
For the **Koji Hub plugin**, this means we print a message each time a request is received by the plugin. A second log message is printed once the task has been successfully created in Koji Hub's database. This also will allow us to measure the time it takes for Koji Hub to insert a task into its database.
Example messages:
```
[Tue Nov 15 19:43:05.996844 2022] [wsgi:error] [pid 17:tid 55] [remote 10.89.0.1:38666] 996 [INFO] m=None u=None p=17 r=?:? koji.plugins: Create osbuildImage task
[...]
[Tue Nov 15 19:43:06.003731 2022] [wsgi:error] [pid 17:tid 55] [remote 10.89.0.1:38666] 2022-11-15 19:43:06,003 [INFO] m=osbuildImage u=kojiadmin p=17 r=10.89.0.1:38666 koji.plugins: osbuildImage task 3 added to database
```
For …

Print more log messages to enable tracking of SLIs

---

plugins/hub/osbuild.py
test/unit/test_hub.py

Previously it the `repo` schema didn't mark the `baseurl` property as
required, although Cloud API requires it and the builder code made
assumptions about it being always provided.
Mark `baseurl` property as required in the `repo` schema and add unit
test for it.

hub: mark baseurl as required in repo schema

---

koji-osbuild.spec

See the relevant Fedora change:
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
We already verified that the SPDX format works well in the Enterprise Linux pipeline.

koji-osbuild.spec: migrate the license field to SPDX
